### ISSUE TITLE
miss you my friend

### ISSUE THREAD

**Issue by deepthawtz** [azer/yolo#1]
@GitCash send 0.008 BCH to my friend @azer 

do you live in Berlin now? My family will be visiting this summer.

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/194/image.png)](https://gitcash.io/claim/azer)
@azer

**Comment by azer** [comment]
@deepthawtz :) thanks! let's e-mail; azer@roadbeats.com
